version: "3.9"
services:
  chat-db:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "chat-db"
      POSTGRES_USER: "sklkv"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5432:5432"
    volumes:
      - chat-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sklkv -d chat-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev.sklkv@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "qwerty"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres
 
volumes:
  chat-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge